// Keep in sync with backend/src/constants/categories.js
export const CATEGORIES = [
  'Singer',
  'Vocalist',
  'Songwriter',
  'Lyricist',
  'Guitarist',
  'Bassist',
  'Pianist',
  'Keyboardist',
  'Drummer',
  'Percussionist',
  'Violinist',
  'Cellist',
  'Saxophonist',
  'Trumpeter',
  'Flutist',
  'Producer',
  'Composer',
  'Beat Maker',
  'DJ',
  'Rapper',
  'Music Director',
  'Session Musician',
  'Mixing Engineer',
  'Mastering Engineer',
  'Sound Engineer',
  'Audio Engineer',
  'Arranger',
];
